---
title: 记一个巨傻×的错误
date: 2017/12/22 9:36
tags: 
---

前两天作分类错误率一直有问题, 排查了一圈最后确定了问题出在数据上, 重新又检查了一遍生成tfrecords的代码:

```python
def encode(filename):
    cwd = os.getcwd()
    root = cwd + '\\' + filename + '\\'
    name = filename + '_Mnist_pgm.tfrecords'
    print(name)
    writer = tf.python_io.TFRecordWriter(name)
    classes = {'0','1','2','3','4','5','6','7','8','9'}

    #for image_filename, label in zip(image_filename_list, label_list):
    for index, name in enumerate(classes):
        class_path = root + name + '\\'
        for img_name in os.listdir(class_path):
            img_path = class_path + img_name
            img = Image.open(img_path)
            print(img_name)
            data = img.tobytes()
            example = tf.train.Example(features=tf.train.Features(feature={
                "label": tf.train.Feature(int64_list=tf.train.Int64List(value=[index])),
                'img_raw': tf.train.Feature(bytes_list=tf.train.BytesList(value=[data]))
            }))
            writer.write(example.SerializeToString())
    writer.close()
 ```

<!-- more -->

问题就出在
```
    classes = {'0','1','2','3','4','5','6','7','8','9'}

    for index, name in enumerate(classes):
```
上.

鬼知道我为啥要把classes写成set, 哪怕是tuple都屁事没有

```python
for index, item in enumerate(['0','1','2','3','4','5','6','7','8','9']):
    print (index, item)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9

for index, item in enumerate({'0','1','2','3','4','5','6','7','8','9'}):
    print (index, item)

0 0
1 4
2 9
3 2
4 5
5 8
6 3
7 1
8 6
9 7

for index, item in enumerate(('0','1','2','3','4','5','6','7','8','9')):
    print (index, item)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
```